// spot@private.orders.v3.api.pb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: PrivateOrdersV3Api.proto

package exchange

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrivateOrdersV3Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SendTime      int64         `protobuf:"varint,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	PrivateOrders *PrivateOrder `protobuf:"bytes,304,opt,name=privateOrders,proto3" json:"privateOrders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateOrdersV3Api) Reset() {
	*x = PrivateOrdersV3Api{}
	mi := &file_PrivateOrdersV3Api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateOrdersV3Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateOrdersV3Api) ProtoMessage() {}

func (x *PrivateOrdersV3Api) ProtoReflect() protoreflect.Message {
	mi := &file_PrivateOrdersV3Api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateOrdersV3Api.ProtoReflect.Descriptor instead.
func (*PrivateOrdersV3Api) Descriptor() ([]byte, []int) {
	return file_PrivateOrdersV3Api_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateOrdersV3Api) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PrivateOrdersV3Api) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PrivateOrdersV3Api) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *PrivateOrdersV3Api) GetPrivateOrders() *PrivateOrder {
	if x != nil {
		return x.PrivateOrders
	}
	return nil
}

type PrivateOrder struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price              string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity           string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Amount             string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	AvgPrice           string                 `protobuf:"bytes,6,opt,name=avgPrice,proto3" json:"avgPrice,omitempty"`
	OrderType          int32                  `protobuf:"varint,7,opt,name=orderType,proto3" json:"orderType,omitempty"`
	TradeType          int32                  `protobuf:"varint,8,opt,name=tradeType,proto3" json:"tradeType,omitempty"`
	RemainAmount       string                 `protobuf:"bytes,10,opt,name=remainAmount,proto3" json:"remainAmount,omitempty"`
	RemainQuantity     string                 `protobuf:"bytes,11,opt,name=remainQuantity,proto3" json:"remainQuantity,omitempty"`
	CumulativeQuantity string                 `protobuf:"bytes,13,opt,name=cumulativeQuantity,proto3" json:"cumulativeQuantity,omitempty"`
	CumulativeAmount   string                 `protobuf:"bytes,14,opt,name=cumulativeAmount,proto3" json:"cumulativeAmount,omitempty"`
	Status             int32                  `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime         int64                  `protobuf:"varint,16,opt,name=createTime,proto3" json:"createTime,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PrivateOrder) Reset() {
	*x = PrivateOrder{}
	mi := &file_PrivateOrdersV3Api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateOrder) ProtoMessage() {}

func (x *PrivateOrder) ProtoReflect() protoreflect.Message {
	mi := &file_PrivateOrdersV3Api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateOrder.ProtoReflect.Descriptor instead.
func (*PrivateOrder) Descriptor() ([]byte, []int) {
	return file_PrivateOrdersV3Api_proto_rawDescGZIP(), []int{1}
}

func (x *PrivateOrder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrivateOrder) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PrivateOrder) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PrivateOrder) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PrivateOrder) GetAvgPrice() string {
	if x != nil {
		return x.AvgPrice
	}
	return ""
}

func (x *PrivateOrder) GetOrderType() int32 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *PrivateOrder) GetTradeType() int32 {
	if x != nil {
		return x.TradeType
	}
	return 0
}

func (x *PrivateOrder) GetRemainAmount() string {
	if x != nil {
		return x.RemainAmount
	}
	return ""
}

func (x *PrivateOrder) GetRemainQuantity() string {
	if x != nil {
		return x.RemainQuantity
	}
	return ""
}

func (x *PrivateOrder) GetCumulativeQuantity() string {
	if x != nil {
		return x.CumulativeQuantity
	}
	return ""
}

func (x *PrivateOrder) GetCumulativeAmount() string {
	if x != nil {
		return x.CumulativeAmount
	}
	return ""
}

func (x *PrivateOrder) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PrivateOrder) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

var File_PrivateOrdersV3Api_proto protoreflect.FileDescriptor

const file_PrivateOrdersV3Api_proto_rawDesc = "" +
	"\n" +
	"\x18PrivateOrdersV3Api.proto\"\x98\x01\n" +
	"\x12PrivateOrdersV3Api\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bsendTime\x18\x06 \x01(\x03R\bsendTime\x124\n" +
	"\rprivateOrders\x18\xb0\x02 \x01(\v2\r.PrivateOrderR\rprivateOrders\"\xa0\x03\n" +
	"\fPrivateOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bavgPrice\x18\x06 \x01(\tR\bavgPrice\x12\x1c\n" +
	"\torderType\x18\a \x01(\x05R\torderType\x12\x1c\n" +
	"\ttradeType\x18\b \x01(\x05R\ttradeType\x12\"\n" +
	"\fremainAmount\x18\n" +
	" \x01(\tR\fremainAmount\x12&\n" +
	"\x0eremainQuantity\x18\v \x01(\tR\x0eremainQuantity\x12.\n" +
	"\x12cumulativeQuantity\x18\r \x01(\tR\x12cumulativeQuantity\x12*\n" +
	"\x10cumulativeAmount\x18\x0e \x01(\tR\x10cumulativeAmount\x12\x16\n" +
	"\x06status\x18\x0f \x01(\x05R\x06status\x12\x1e\n" +
	"\n" +
	"createTime\x18\x10 \x01(\x03R\n" +
	"createTimeBH\n" +
	"\x1ccom.mxc.push.common.protobufB\x17PrivateOrdersV3ApiProtoH\x01P\x01Z\v./;exchangeb\x06proto3"

var (
	file_PrivateOrdersV3Api_proto_rawDescOnce sync.Once
	file_PrivateOrdersV3Api_proto_rawDescData []byte
)

func file_PrivateOrdersV3Api_proto_rawDescGZIP() []byte {
	file_PrivateOrdersV3Api_proto_rawDescOnce.Do(func() {
		file_PrivateOrdersV3Api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PrivateOrdersV3Api_proto_rawDesc), len(file_PrivateOrdersV3Api_proto_rawDesc)))
	})
	return file_PrivateOrdersV3Api_proto_rawDescData
}

var file_PrivateOrdersV3Api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PrivateOrdersV3Api_proto_goTypes = []any{
	(*PrivateOrdersV3Api)(nil), // 0: PrivateOrdersV3Api
	(*PrivateOrder)(nil),       // 1: PrivateOrder
}
var file_PrivateOrdersV3Api_proto_depIdxs = []int32{
	1, // 0: PrivateOrdersV3Api.privateOrders:type_name -> PrivateOrder
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PrivateOrdersV3Api_proto_init() }
func file_PrivateOrdersV3Api_proto_init() {
	if File_PrivateOrdersV3Api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PrivateOrdersV3Api_proto_rawDesc), len(file_PrivateOrdersV3Api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PrivateOrdersV3Api_proto_goTypes,
		DependencyIndexes: file_PrivateOrdersV3Api_proto_depIdxs,
		MessageInfos:      file_PrivateOrdersV3Api_proto_msgTypes,
	}.Build()
	File_PrivateOrdersV3Api_proto = out.File
	file_PrivateOrdersV3Api_proto_goTypes = nil
	file_PrivateOrdersV3Api_proto_depIdxs = nil
}
